name: Terragrunt Build, Deploy
on:
  push:
    branches: [ main ]

jobs:
  terragrunt-validate-build-test:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-session-name: Terragrunt-Validate-Build-Test-Workflow
      - name: Prepare Environment
        shell: bash
        env: 
          # PYTHON
          PYTHONPATH: src
          PYTHONTRACEMALLOC: 25

          # WORKSPACE
          WORKSPACE_ID: testing
          WORKSPACE_NAME : Testing Environment

          # APP REPOSITORY
          VCS_PROVIDER: github
          REPO_ACCOUNT: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_REFERENCE: ${{ github.ref_name }}
          REPO_TYPE: ${{ github.repository_visibility }}
          USER_NAME: ${{ github.triggering_actor }}
          USER_EMAIL: ${{ github.event.pusher.email }}

          # VERSIONS
          TERRAFORM_VERSION: 1.2.7
          TERRAGRUNT_VERSION: 0.38.7

          # TERRAGRUNT
          RUN_ALL: true
          TG_COMMAND: apply
          TG_ARGUMENTS:
          RUN_MODULE: 
          STACK_FOLDER: live
          BUCKET_SUFFIX: github
          INTERACTIVE: false

          # AWS
          TARGET_AWS_REGION: eu-west-1
          TARGET_AWS_ACCOUNT_NAME: testing
          TARGET_AWS_ACCOUNT_ID: 553688522943
          TARGET_AWS_PROFILE: leia-testing
          PIPELINE_AWS_REGION: eu-west-1
          PIPELINE_AWS_PROFILE: leia-pipeline
          PIPELINE_AWS_ACCOUNT_ID: 377449198785
          ECR_AWS_ACCOUNT_ID: 377449198785
          SQS_AWS_PROFILE: leia-pipeline

          # REPLACE Parameters
          DOMAIN: testing.dev.leiarenee.io
          DNS_ZONE_ID: Z0890541BQO7OVB8F6WL
          CERTIFICATE: arn:aws:acm:eu-west-1:377449198785:certificate/431ea958-254b-4f8c-995f-a311559fcce5
          CLUSTER: my-testing-k8s

          # PIPELINE
          RUNNER_MACHINE: github-actions
          WORK_FOLDER_NAME: temp-volume
          INITIAL_PROGRESS: 10
          MODULES_FINAL_PROGRESS: 90
          FINAL_PROGRESS: 95
          S3_JOBS_BUCKET: sf-pipeline-jobs
          EVENTBRIDGE_RULE: SF-Cron-Pipeline
          UPLOAD_WORKFOLDER: always
          UPLOAD_JOB_RESOURCES: true
          UPLOAD_PLAN_FILES: true
          SEND_SQS_MESSAGES: true

          # JOB
          JOB_DEFINITION: arn:aws:batch:eu-west-1:377449198785:job-definition/tf_pipeline_job_definition
          JOB_QUEUE: arn:aws:batch:eu-west-1:377449198785:job-queue/tf-deployment-job-queue

          # ROLE
          ROLE_EVENTBRIDGE: arn:aws:iam::377449198785:role/service-role/Amazon_EventBridge_Invoke_Batch_Job_Queue

          # TTL
          TTL_DURATION_MINUTES: 10

          # STEP FUNCTIONS
          PIPELINE_STATE_MACHINE_NAME: Pipeline-State-Machine-enabling-drake
          PIPELINE_SF_TEMPLATE_FILE: ./sf-run/sf-template.json

          # SQS POLLING
          POLL_INTERVAL: 30
          MAX_SQS_MESSAGES: 10

          # RUNTIME
          ECHO_COMMANDS: true

        run: echo start deploy
