name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      workspaceId:
        description: Workspace Id (Changes tfstate bucket)    
        default: testing
        type: choice
        options:
        - Testing
        - Staging
        - Production-1
        - Production-2
        - Leia-Renee
      targetAwsAccountId:
        description: Target AWS Account Id   
        default: 553688522943
        type: choice
        options:
        - 553688522943 # testing
        - 518854297938 # Staging
        - 009403416359 # Prod1
        - 230794785515 # Prod2
        - 684353670650 # Dev Leia
      targetAwsRegion:
        description: Target AWS Region     
        default: eu-west-1
        type: choice
        options:
        - eu-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - eu-south-1
        - eu-north-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
      runAll:
        description: Terragrunt run-all
        default: true 
        type: boolean
      tgCommand: 
        description: Terragrunt command
        default: apply
        type: choice
        options:
        - validate
        - plan
        - apply
        - destroy
        - show
        - output
      tgArguments:
        description: TG Cli arguments
      stackFolder:
        description: Main Stack Folder
        default: live
        type: choice
        options:
        - live
        - test
      runModule:
        description: Terragrunt Module Folder [See here](https://github.com/leiarenee/sf-infra/tree/main/infra/live)
        default:
      ttlDuration:
        description: Time to Live in minutes 
        default: 30

jobs:
  terragrunt-validate-build-test:
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-session-name: Terragrunt-Validate-Build-Test-Workflow
      - name: Execute Pipeline
        shell: bash
        env: 
          # PYTHON
          PYTHONPATH: src
          PYTHONTRACEMALLOC: 25

          # WORKSPACE
          WORKSPACE_ID: ${{ github.event.inputs.workspaceId }}

          # APP REPOSITORY
          VCS_PROVIDER: github
          REPO_ACCOUNT: leiarenee
          REPO_NAME: sf-infra
          REPO_REFERENCE: ${{ github.ref }}
          REPO_TYPE: public
          USER_NAME: ${{ github.triggering_actor }}
          USER_EMAIL: ${{ github.event.pusher.email }}

          # VERSIONS
          TERRAFORM_VERSION: 1.2.7
          TERRAGRUNT_VERSION: 0.38.7

          # TERRAGRUNT
          RUN_ALL: ${{ github.event.inputs.runAll }}
          TG_COMMAND: ${{ github.event.inputs.tgCommand }}
          TG_ARGUMENTS: ${{ github.event.inputs.tgArguments }}
          RUN_MODULE: ${{ github.event.inputs.runModule }}
          STACK_FOLDER: ${{ github.event.inputs.stackFolder }}
          BUCKET_SUFFIX: github
          INTERACTIVE: false
          FORCE_INIT: false
          COMPACT_WARNINGS: true
          COMPACT_STDOUT: true
          LOG_LEVEL: info

          # AWS
          TARGET_AWS_REGION: ${{ github.event.inputs.targetAwsRegion }}
          TARGET_AWS_ACCOUNT_NAME: Testing Environment
          TARGET_AWS_ACCOUNT_ID: ${{ github.event.inputs.targetAwsAccountId }}
          TARGET_AWS_PROFILE: testing
          TARGET_AWS_SECRET: TARGET_AWS_ACCESS
          PIPELINE_AWS_REGION: eu-west-1
          PIPELINE_AWS_PROFILE: pipeline
          PIPELINE_AWS_ACCOUNT_ID: 377449198785
          PIPELINE_AWS_SECRET: PIPELINE_AWS_ACCESS
          ECR_AWS_ACCOUNT_ID: 377449198785
          SQS_AWS_PROFILE: pipeline

          # REPLACE Parameters
          DOMAIN: testing.dev.leiarenee.io
          DNS_ZONE_ID: Z0890541BQO7OVB8F6WL
          CERTIFICATE: arn:aws:acm:eu-west-1:377449198785:certificate/431ea958-254b-4f8c-995f-a311559fcce5
          CLUSTER: my-testing-k8s

          # PIPELINE
          RUNNER_MACHINE: github-actions
          WORK_FOLDER_NAME: temp-volume
          INITIAL_PROGRESS: 10
          MODULES_FINAL_PROGRESS: 90
          FINAL_PROGRESS: 95
          S3_JOBS_BUCKET: sf-pipeline-jobs
          EVENTBRIDGE_RULE: SF-Cron-Pipeline
          UPLOAD_WORKFOLDER: always
          UPLOAD_JOB_RESOURCES: true
          UPLOAD_PLAN_FILES: true
          SEND_SQS_MESSAGES: true

          # JOB
          JOB_DEFINITION: arn:aws:batch:eu-west-1:377449198785:job-definition/tf_pipeline_job_definition
          JOB_QUEUE: arn:aws:batch:eu-west-1:377449198785:job-queue/tf-deployment-job-queue

          # ROLE
          ROLE_EVENTBRIDGE: arn:aws:iam::377449198785:role/service-role/Amazon_EventBridge_Invoke_Batch_Job_Queue

          # TTL
          TTL_DURATION_MINUTES: ${{ github.event.inputs.ttlDuration }}

          # STEP FUNCTIONS
          PIPELINE_STATE_MACHINE_NAME: Pipeline-State-Machine-enabling-drake
          PIPELINE_SF_TEMPLATE_FILE: sf-template.json

          # SQS POLLING
          POLL_INTERVAL: 5
          MAX_SQS_MESSAGES: 10

          # RUNTIME
          ECHO_COMMANDS: false

          # GITHUB
          # GITHUB_CONTEXT: ${{ toJson(github) }} 

        run: ./sf-run/sf-execute.sh
      - name: Trace Target Deploy Logs 
        shell: bash
        run: ./sf-run/sqs-poll.sh



