name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Branch
        #https://github.com/marketplace/actions/pull-request-comment-branch
        uses: xt0rted/pull-request-comment-branch@v1 
        id: comment-branch
      - name: Slash Command Dispatch
        if: ${{ github.event.issue.pull_request }}
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.PAT_WORKFLOW }}
          commands: |
            run
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            repoReference=${{ steps.comment-branch.outputs.head_ref }}
            ref=${{ steps.comment-branch.outputs.head_ref }}
          # 
            